<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Carrera extends Model
{
    public const CARRERAS = [
        2 => 'INGENIERÍA EN COMPUTACIÓN',
        3 => 'INGENIERO EN DISEÑO',
        4 => 'INGENIERÍA EN ELECTRÓNICA',
        5 => 'LICENCIATURA EN CIENCIAS EMPRESARIALES',
        6 => 'INGENIERÍA EN ALIMENTOS',
        7 => 'LICENCIATURA EN MATEMÁTICAS APLICADAS',
        8 => 'MAESTRÍA EN ELECTRÓNICA Y COMPUTACIÓN',
        9 => 'DOCTORADO EN ELECTRÓNICA Y COMPUTACIÓN',
        10 => 'MAESTRÍA EN COMPUTACIÓN CON ESPECIALIDAD EN SISTEMAS DISTRIBUIDOS',
        11 => 'INGENIERÍA INDUSTRIAL',
        12 => 'LICENCIATURA EN ESTUDIOS MEXICANOS',
        13 => 'MAESTRÍA EN INGENIERÍA EN SOFTWARE',
        14 => 'INGENIERÍA MECATRÓNICA',
        15 => 'MAESTRÍA EN ADMINISTRACIÓN DE NEGOCIOS',
        16 => 'MAESTRÍA EN MEDIOS INTERACTIVOS',
        17 => 'INGENIERÍA EN FÍSICA APLICADA',
        18 => 'MAESTRÍA EN CIENCIAS: PRODUCTOS NATURALES Y ALIMENTOS',
        19 => 'MAESTRÍA EN TECNOLOGÍA AVANZADA DE MANUFACTURA',
        20 => 'MAESTRÍA EN TECNOLOGÍAS DE CÓMPUTO APLICADO',
        21 => 'MAESTRÍA EN ELECTRÓNICA, OPCIÓN: SISTEMAS INTELIGENTES APLICADOS',
        22 => 'MAESTRÍA EN MODELACIÓN MATEMÁTICA',
        23 => 'MAESTRÍA EN DISEÑO DE MUEBLES',
        24 => 'MAESTRÍA EN DISEÑO DE MODAS',
        25 => 'MAESTRÍA EN ROBÓTICA',
        26 => 'DOCTORADO EN TECNOLOGÍAS DE CÓMPUTO APLICADO E INGENIERÍA DE LA COMPUTACIÓN',
        27 => 'DOCTORADO EN ELECTRÓNICA, OPCIÓN: SISTEMAS INTELIGENTES APLICADOS',
        28 => 'DOCTORADO EN ROBÓTICA',
        29 => 'DOCTORADO EN MODELACIÓN MATEMÁTICA',
        30 => 'MAESTRÍA EN CIENCIAS DE MATERIALES',
        31 => 'INGENIERÍA MECÁNICA AUTOMOTRIZ',
        32 => 'INGENIERÍA CIVIL',
        33 => 'DOCTORADO EN CIENCIAS: PRODUCTOS NATURALES Y ALIMENTOS',
        34 => 'MAESTRÍA EN INTELIGENCIA ARTIFICIAL',
        35 => 'DOCTORADO EN INTELIGENCIA ARTIFICIAL',
        36 => 'INGENIERÍA QUÍMICA EN PROCESOS SOSTENIBLES',
        37 => 'MAESTRÍA EN CIENCIA DE DATOS'
    ];

    public static function obtenerCarreras()
    {
        return self::CARRERAS;
    }

    public static function obtenerNombre($id)
    {
        return self::CARRERAS[$id] ?? "Carrera no encontrada.";
    }
}
